In [1]:
import numpy as np

In [2]:
# creating  1d numpy array
mylist1 = [101,102,103]
myarray = np.array(mylist1)
print(myarray)

[101 102 103]


In [4]:
# creating a 2d numpy array
mylist2 = [101,102,103]
myarray2D = np.array([mylist1,mylist2])
print(myarray2D)
                

[[101 102 103]
 [101 102 103]]


In [8]:
# finding the dimension of the array - shape
print('myarray dimensions')
print(myarray.shape)
print('myarray 2D dimensions')
print(myarray2D.shape)

     

myarray dimensions
(3,)
myarray 2D dimensions
(2, 3)


In [9]:
#finding the datatype of the array -dtype
print('myarray datatype')
print(myarray.dtype)
print('myarray 2D datatype')
print(myarray2D.dtype)


myarray datatype
int32
myarray 2D datatype
int32


In [21]:
# array creation and intilization functions -zeros
zero_array = np.zeros (5)
print(zero_array)

zero_array2D = np.zeros([5,5])
print(zero_array2D)
                      

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
# array creation and intilization functions -ones
print('1D')
zero_array = np.ones (5)
print(zero_array)
print('2D')
zero_array2D = np.ones([5,5])
print(zero_array2D)
                      

1D
[1. 1. 1. 1. 1.]
2D
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
# array creation and intilization functions -empty

print('1D')
zero_array = np.empty (5)
print(zero_array)
print('2D')
zero_array2D = np.empty([5,5])
print(zero_array2D)
            

1D
[1. 1. 1. 1. 1.]
2D
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
# array creation and intilization functions -eye

Identity_array = np.eye(3)
print(Identity_array)
    

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
# array creation and intilization functions -arange 

Ap_array = np.arange(0,50,2)
print(Ap_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
