In [1]:
import numpy as np


In [6]:
#scalar array multiplication- using * operator 

arr1 = np.array([[1,2,3],[5,6,7]])
print(arr1)

[[1 2 3]
 [5 6 7]]


In [7]:
arr2 = arr1*arr1
print(arr2)


[[ 1  4  9]
 [25 36 49]]


In [8]:
# Exponential multiplication using ** operator 
arr3 = arr1**2
print(arr3)

[[ 1  4  9]
 [25 36 49]]


In [9]:
# scalar subraction of array elements 

arr4 = arr3 - arr1
print(arr4)

[[ 0  2  6]
 [20 30 42]]


In [10]:
# scalar Divison of array elements 

arr5 = 1/arr1
print(arr5)

[[1.         0.5        0.33333333]
 [0.2        0.16666667 0.14285714]]
